# -------- Build stage --------
FROM golang:1.25 AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .

ENV CGO_ENABLED=0 GOOS=linux
RUN go build -trimpath -ldflags="-s -w" -o /memo-cli ./client/cmd/cli

# -------- Runtime stage --------
FROM gcr.io/distroless/base-debian11
COPY --from=builder /memo-cli /memo-cli

ENTRYPOINT ["/memo-cli"]