apiVersion: v1
kind: Service
metadata:
  name: memo-server
  namespace: memo
spec:
  selector:
    app: memo-server
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
      protocol: TCP
  type: ClusterIP