// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: api/memo.proto

package memo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Memo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                 // サーバーでUUID生成
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`                           // 1〜100文字
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`                       // 0〜2000文字
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Unix epoch millis
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Memo) Reset() {
	*x = Memo{}
	mi := &file_api_memo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Memo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Memo) ProtoMessage() {}

func (x *Memo) ProtoReflect() protoreflect.Message {
	mi := &file_api_memo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Memo.ProtoReflect.Descriptor instead.
func (*Memo) Descriptor() ([]byte, []int) {
	return file_api_memo_proto_rawDescGZIP(), []int{0}
}

func (x *Memo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Memo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Memo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Memo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type CreateMemoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMemoRequest) Reset() {
	*x = CreateMemoRequest{}
	mi := &file_api_memo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMemoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMemoRequest) ProtoMessage() {}

func (x *CreateMemoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_memo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMemoRequest.ProtoReflect.Descriptor instead.
func (*CreateMemoRequest) Descriptor() ([]byte, []int) {
	return file_api_memo_proto_rawDescGZIP(), []int{1}
}

func (x *CreateMemoRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateMemoRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type CreateMemoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Memo          *Memo                  `protobuf:"bytes,1,opt,name=memo,proto3" json:"memo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMemoResponse) Reset() {
	*x = CreateMemoResponse{}
	mi := &file_api_memo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMemoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMemoResponse) ProtoMessage() {}

func (x *CreateMemoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_memo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMemoResponse.ProtoReflect.Descriptor instead.
func (*CreateMemoResponse) Descriptor() ([]byte, []int) {
	return file_api_memo_proto_rawDescGZIP(), []int{2}
}

func (x *CreateMemoResponse) GetMemo() *Memo {
	if x != nil {
		return x.Memo
	}
	return nil
}

type GetMemoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMemoRequest) Reset() {
	*x = GetMemoRequest{}
	mi := &file_api_memo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMemoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemoRequest) ProtoMessage() {}

func (x *GetMemoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_memo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemoRequest.ProtoReflect.Descriptor instead.
func (*GetMemoRequest) Descriptor() ([]byte, []int) {
	return file_api_memo_proto_rawDescGZIP(), []int{3}
}

func (x *GetMemoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetMemoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Memo          *Memo                  `protobuf:"bytes,1,opt,name=memo,proto3" json:"memo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMemoResponse) Reset() {
	*x = GetMemoResponse{}
	mi := &file_api_memo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMemoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemoResponse) ProtoMessage() {}

func (x *GetMemoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_memo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemoResponse.ProtoReflect.Descriptor instead.
func (*GetMemoResponse) Descriptor() ([]byte, []int) {
	return file_api_memo_proto_rawDescGZIP(), []int{4}
}

func (x *GetMemoResponse) GetMemo() *Memo {
	if x != nil {
		return x.Memo
	}
	return nil
}

type ListMemosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMemosRequest) Reset() {
	*x = ListMemosRequest{}
	mi := &file_api_memo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMemosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMemosRequest) ProtoMessage() {}

func (x *ListMemosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_memo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMemosRequest.ProtoReflect.Descriptor instead.
func (*ListMemosRequest) Descriptor() ([]byte, []int) {
	return file_api_memo_proto_rawDescGZIP(), []int{5}
}

type ListMemosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Memos         []*Memo                `protobuf:"bytes,1,rep,name=memos,proto3" json:"memos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMemosResponse) Reset() {
	*x = ListMemosResponse{}
	mi := &file_api_memo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMemosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMemosResponse) ProtoMessage() {}

func (x *ListMemosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_memo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMemosResponse.ProtoReflect.Descriptor instead.
func (*ListMemosResponse) Descriptor() ([]byte, []int) {
	return file_api_memo_proto_rawDescGZIP(), []int{6}
}

func (x *ListMemosResponse) GetMemos() []*Memo {
	if x != nil {
		return x.Memos
	}
	return nil
}

type DeleteMemoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMemoRequest) Reset() {
	*x = DeleteMemoRequest{}
	mi := &file_api_memo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMemoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMemoRequest) ProtoMessage() {}

func (x *DeleteMemoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_memo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMemoRequest.ProtoReflect.Descriptor instead.
func (*DeleteMemoRequest) Descriptor() ([]byte, []int) {
	return file_api_memo_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteMemoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteMemoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMemoResponse) Reset() {
	*x = DeleteMemoResponse{}
	mi := &file_api_memo_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMemoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMemoResponse) ProtoMessage() {}

func (x *DeleteMemoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_memo_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMemoResponse.ProtoReflect.Descriptor instead.
func (*DeleteMemoResponse) Descriptor() ([]byte, []int) {
	return file_api_memo_proto_rawDescGZIP(), []int{8}
}

var File_api_memo_proto protoreflect.FileDescriptor

const file_api_memo_proto_rawDesc = "" +
	"\n" +
	"\x0eapi/memo.proto\x12\amemo.v1\"e\n" +
	"\x04Memo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\"C\n" +
	"\x11CreateMemoRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"7\n" +
	"\x12CreateMemoResponse\x12!\n" +
	"\x04memo\x18\x01 \x01(\v2\r.memo.v1.MemoR\x04memo\" \n" +
	"\x0eGetMemoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"4\n" +
	"\x0fGetMemoResponse\x12!\n" +
	"\x04memo\x18\x01 \x01(\v2\r.memo.v1.MemoR\x04memo\"\x12\n" +
	"\x10ListMemosRequest\"8\n" +
	"\x11ListMemosResponse\x12#\n" +
	"\x05memos\x18\x01 \x03(\v2\r.memo.v1.MemoR\x05memos\"#\n" +
	"\x11DeleteMemoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x14\n" +
	"\x12DeleteMemoResponse2\x9d\x02\n" +
	"\vMemoService\x12E\n" +
	"\n" +
	"CreateMemo\x12\x1a.memo.v1.CreateMemoRequest\x1a\x1b.memo.v1.CreateMemoResponse\x12<\n" +
	"\aGetMemo\x12\x17.memo.v1.GetMemoRequest\x1a\x18.memo.v1.GetMemoResponse\x12B\n" +
	"\tListMemos\x12\x19.memo.v1.ListMemosRequest\x1a\x1a.memo.v1.ListMemosResponse\x12E\n" +
	"\n" +
	"DeleteMemo\x12\x1a.memo.v1.DeleteMemoRequest\x1a\x1b.memo.v1.DeleteMemoResponseB#Z!example.com/memo/api/memo/v1;memob\x06proto3"

var (
	file_api_memo_proto_rawDescOnce sync.Once
	file_api_memo_proto_rawDescData []byte
)

func file_api_memo_proto_rawDescGZIP() []byte {
	file_api_memo_proto_rawDescOnce.Do(func() {
		file_api_memo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_memo_proto_rawDesc), len(file_api_memo_proto_rawDesc)))
	})
	return file_api_memo_proto_rawDescData
}

var file_api_memo_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_memo_proto_goTypes = []any{
	(*Memo)(nil),               // 0: memo.v1.Memo
	(*CreateMemoRequest)(nil),  // 1: memo.v1.CreateMemoRequest
	(*CreateMemoResponse)(nil), // 2: memo.v1.CreateMemoResponse
	(*GetMemoRequest)(nil),     // 3: memo.v1.GetMemoRequest
	(*GetMemoResponse)(nil),    // 4: memo.v1.GetMemoResponse
	(*ListMemosRequest)(nil),   // 5: memo.v1.ListMemosRequest
	(*ListMemosResponse)(nil),  // 6: memo.v1.ListMemosResponse
	(*DeleteMemoRequest)(nil),  // 7: memo.v1.DeleteMemoRequest
	(*DeleteMemoResponse)(nil), // 8: memo.v1.DeleteMemoResponse
}
var file_api_memo_proto_depIdxs = []int32{
	0, // 0: memo.v1.CreateMemoResponse.memo:type_name -> memo.v1.Memo
	0, // 1: memo.v1.GetMemoResponse.memo:type_name -> memo.v1.Memo
	0, // 2: memo.v1.ListMemosResponse.memos:type_name -> memo.v1.Memo
	1, // 3: memo.v1.MemoService.CreateMemo:input_type -> memo.v1.CreateMemoRequest
	3, // 4: memo.v1.MemoService.GetMemo:input_type -> memo.v1.GetMemoRequest
	5, // 5: memo.v1.MemoService.ListMemos:input_type -> memo.v1.ListMemosRequest
	7, // 6: memo.v1.MemoService.DeleteMemo:input_type -> memo.v1.DeleteMemoRequest
	2, // 7: memo.v1.MemoService.CreateMemo:output_type -> memo.v1.CreateMemoResponse
	4, // 8: memo.v1.MemoService.GetMemo:output_type -> memo.v1.GetMemoResponse
	6, // 9: memo.v1.MemoService.ListMemos:output_type -> memo.v1.ListMemosResponse
	8, // 10: memo.v1.MemoService.DeleteMemo:output_type -> memo.v1.DeleteMemoResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_memo_proto_init() }
func file_api_memo_proto_init() {
	if File_api_memo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_memo_proto_rawDesc), len(file_api_memo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_memo_proto_goTypes,
		DependencyIndexes: file_api_memo_proto_depIdxs,
		MessageInfos:      file_api_memo_proto_msgTypes,
	}.Build()
	File_api_memo_proto = out.File
	file_api_memo_proto_goTypes = nil
	file_api_memo_proto_depIdxs = nil
}
